config/routes.rb
Rails.application.routes.draw do

  get 'home/index' => "home#index"
  get "home/about" => "home#about"
  devise_for :users

  get "users/:id" => "users#show", as: "show_user"
  delete "books/:id" => "books#destroy", as: "destroy_book"

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
resources :users, only: [:new, :create, :index, :show, :edit, :update, :sessions, :paswords, :registrations]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true,length: { minimum:2, maximum: 20 }
  validates :introduction, length: {maximum: 50 }

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
   end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
  devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end
  def index
  	@users = User.all
    @user_id = User.find(current_user.id)
    @book = Book.new
  end
def edit
  @user = User.find(params[:id])
end
def update
  @user = User.find(params[:id])
  if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
  redirect_to user_path(@user.id) and return
end
else
   @users = User.all
   render action: :edit
end
private
    def user_params
        params.require(:user).permit(:name, :profile_image, :introduction)
    end
    def correct_user
      user = User.find(params[:id])
      if current_user != user
        redirect_to show_user_path(current_user.id)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_new_book.html.erb
<h2>New book</h2>

<%= form_for(book) do |f| %>
 
    <h4>Title</h4>
    <%= f.text_field :title, :size=> "36X10" %>
 
    <h4>Opinion</h4>
    <%= f.text_area :body, :size=> "35X10" %><br>
 
    <%= f.submit('Create Book',class: 'btn btn-primary btn-block') %>
    <% end %>

app/views/users/_user_info.html.erb
<h1>User info</h1>

<%= attachment_image_tag user_id, :profile_image, :fill, 100, 100, format: "jpeg", class: "img-square pull-left image", fallback: "no_image.jpg" %>

<table class="table">
<tr><td>name</td><td><%= user_id.name %></td></tr>
<tr><td>introduction</td><td><%= user_id.introduction %></td></tr>
</table>

<%= link_to edit_user_path(user_id), class: "btn btn-default btn-block" do %>
<i class="glyphicon glyphicon-wrench"></i>
<span></span>
<% end %>

</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">

<h1>User info</h1>

<%= form_for(@user) do |f| %>

<% if @user.errors.any? %>
 <div id="error_explanation">
    <p><%= @user.errors.count %>errors prohibited this obj from being saved:</p>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
 
  <h4>Name</h4>
  <%= f.text_field :name %>

  <h4>Image</h4>
  <%= f.attachment_field :profile_image %>
 
  <h4>Introduction</h4>
  <%= f.text_area :introduction %><br>
 
  <%= f.submit 'Update User' %>
 
<% end %>

<p class="text-right">CopyRight Infratop.inc</p>
</div>
</div>

app/views/users/index.html.erb
 <% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

 <div class="container">
  <div class="row">
    <div class="col-xs-3">

<%= render 'users/user_info', user_id: @user_id %>

<%= render 'users/new_book', book: @book %>

</div>

<div class="col-xs-9">
 <h1>Users</h1>

<table class="table">
    <thead>
    <tr>
   	  <th><p>image</p></th>
      <th><p>name</p></th>
      <th><p></p></th>
    </tr>
    </thead>
<% @users.each do |user| %>
   <tbody>
    <tr>
   <span><td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: "jpeg", class: "img-square pull-left image", fallback: "no_image.jpg",size:'50x50' %></td></span>
   <td><span><%= user.name %></span></td>
   <td><%=link_to "Show", show_user_path(user.id) %></td>
   </tr>

    <% end %>
</tbody>
</table>
</div>
<p class="text-right">CopyRight Infratop.inc</p>
</div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-3">

<%= render 'users/user_info', user_id: @user %>

<%= render 'users/new_book', book: @book %>
 
</div>

<div class="col-xs-9">
    <h1>Books</h1>

<table class="table table-hover">
    <thead>
    <tr>
      <th><p></p></th>
      <th><p>Title</p></th>
      <th><p>Opinion</p></th>
    </tr>
    </thead>
<% @books.each do |book| %>
    <tbody>
    <tr>
      <td>
        <%=link_to show_user_path(book.user.id) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: "jpeg", class: "img-square pull-left image", fallback: "no_image.jpg",size:'50x50' %>
      <% end %>
      </td>
      <td><span><%=link_to book.title, book_path(book.id) %></span></td>
      <td><span><%= book.body %></span></td>
    </tr>
   <% end %>
   </tbody>
   </table>
   <p class="text-right">CopyRight Infratop.inc</p>
 </div>
</div>
</div>