config/routes.rb
Rails.application.routes.draw do

  get 'home/index' => "home#index"
  get "home/about" => "home#about"
  devise_for :users

  get "users/:id" => "users#show", as: "show_user"
  delete "books/:id" => "books#destroy", as: "destroy_book"

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
resources :users, only: [:new, :create, :index, :show, :edit, :update, :sessions, :paswords, :registrations]
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true,length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    before_action :correct_user, only: [:edit, :update]

	def new
		@book = Book.new
    end
    def create
    	@book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save
            flash[:notice] = "You have created book successfully."
        redirect_to book_path(@book.id)
    else
        @books = Book.all
        @user_id = User.find(current_user.id)
        render action: :index
    end
   end
    def index
        @books = Book.all
        @book = Book.new
        @user_id = User.find(current_user.id)
    end
    def show
        @book1 = Book.find(params[:id])
        @book = Book.new
        @user_id = @book1.user
    end
    def edit
        @book = Book.find(params[:id])
    end
    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            flash[:notice] = "You have updated book successfully."
        redirect_to book_path and return
    end
    else
        @books = Book.all
        render action: :edit
    end
    def destroy
        book = Book.find(params[:id])
        book.destroy
        redirect_to book_path
    end
    private
    def book_params
      params.require(:book).permit(:title, :body)
    end
    def correct_user
        book = Book.find(params[:id])
        if current_user.id != book.user.id
            redirect_to books_path
        end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_for(@book) do |f| %>

<% if @book.errors.any? %>
 <div id="error_explanation">
    <p><%= @book.errors.count %>errors prohibited this obj from being saved:</p>
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>
    <br>
    <%= link_to "Show", book_path(@book.id) %>
    <%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
 <div class="container">
  <div class="row">

    <% if @book.errors.any? %>
 <div id="error_explanation">
    <p><%= @book.errors.count %>errors prohibited this obj from being saved:</p>
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

    <div class="col-xs-3">

 <%= render 'users/user_info', user_id: @user_id %>

<%= render 'users/new_book', book: @book %>
 
</div>

<div class="col-xs-9">
 <h1>Books</h1>

<table class="table table-hover">
   	<thead>
   	<tr>
   	  <th><p></p></th>
      <th><p>Title</p></th>
      <th><p>Opinion</p></th>
    </tr>
    </thead>
<% @books.each do |book| %>
    <tbody>
    <tr>
     <td>
      <%=link_to show_user_path(book.user.id) do %>
      <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: "jpeg", class: "img-square pull-left image", fallback: "no_image.jpg",size:'50x50' %>
      <% end %>
      </td>
      <td><span>

      	<%=link_to book.title, book_path(book.id)  %>
      		
      	</span></td>
      <td><span><%= book.body %></span></td>
    </tr>
    </tbody>
    <% end %>
  </table>
  <p class="text-right">CopyRight Infratop.inc</p>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= form_for(@book) do |f| %>
 
    <h4>Title</h4>
    <%= f.text_field :title %>
 
    <h4>Opinion</h4>
    <%= f.text_area :body %>
 
    <%= f.submit 'Create Book' %>
 
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

 <div class="container">
  <div class="row">
    <div class="col-xs-3">

     <%= render 'users/user_info', user_id: @user_id %>

     <%= render 'users/new_book', book: @book %>
 
    </div>

   <div class="col-xs-9">

    <h1>Book detail</h1>

   <table class="table">
  
    <tbody>
     <tr>
     <td>
      <%=link_to show_user_path(@book1.user.id) do %>
      <%= attachment_image_tag @book1.user, :profile_image, :fill, 40, 40, format: "jpeg", class: "img-square pull-left image", fallback: "no_image.jpg", size: "40x40" %><br><br>
      <%= @user_id.name %>
      <% end %>
     </td>
     <td><p><%=link_to @book1.title, book_path(@book1.id) %></p></td>
     <td><p><%= @book1.body %></p></td>
     <% if @book1.user_id == current_user.id %>
     <td><%=link_to "Edit", edit_book_path(@book1.id) %></td>
     <td><%=link_to "Destroy", destroy_book_path(@book1.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
     <% end %>
     </tr>
   </tbody> 
   </table>
   <p class="text-right">CopyRight Infratop.inc</p>
   </div>
  </div>
 </div>